Update Dockerfile to use python3 instead of python
This fixes a build problem caused by missing python:

    ERROR: unsatisfiable constraints:
      python (missing):
        required by: world[python]

Signed-off-by: Stefan Weil <sw@weilnetz.de>